"""
Lord of the Rings themed demo data for Fake SIS.
Characters as students, staff, and guardians.
"""
from datetime import date
from uuid import uuid4

# Fixed UUIDs for consistent data
ORGS = {
    "middle_earth": str(uuid4()),
    "rivendell_academy": str(uuid4()),
    "rivendell_grundskola": str(uuid4()),
    "rivendell_gymnasium": str(uuid4()),
}

GROUPS = {
    "4a_shire": str(uuid4()),
    "4b_buckland": str(uuid4()),
    "5a_gondor": str(uuid4()),
    "gy1_fellowship": str(uuid4()),
    "gy2_elven": str(uuid4()),
}

PERSONS = {
    # Staff
    "gandalf": str(uuid4()),
    "elrond": str(uuid4()),
    "galadriel": str(uuid4()),
    "celeborn": str(uuid4()),
    "aragorn": str(uuid4()),
    "bilbo": str(uuid4()),
    "tom_bombadil": str(uuid4()),

    # Students
    "frodo": str(uuid4()),
    "sam": str(uuid4()),
    "merry": str(uuid4()),
    "pippin": str(uuid4()),
    "faramir": str(uuid4()),
    "eowyn": str(uuid4()),
    "arwen": str(uuid4()),
    "legolas": str(uuid4()),
    "boromir": str(uuid4()),
    "eomer": str(uuid4()),

    # Guardians (some overlap with staff)
    "hamfast": str(uuid4()),
    "saradoc": str(uuid4()),
    "paladin": str(uuid4()),
    "denethor": str(uuid4()),
    "theoden": str(uuid4()),
    "thranduil": str(uuid4()),
}

# Organisation hierarchy
ORGANISATIONS = [
    {
        "id": ORGS["middle_earth"],
        "display_name": "Middle-earth Educational Authority",
        "organisation_type": "Huvudman",
        "organisation_number": "802100-1234",
        "municipality_code": "0180",
        "email": "info@middle-earth.edu",
        "phone_number": "08-123 45 67",
        "url": "https://middle-earth.edu",
        "street_address": "Valinor väg 1",
        "postal_code": "111 22",
        "locality": "Aman",
    },
    {
        "id": ORGS["rivendell_academy"],
        "display_name": "Rivendell Academy",
        "organisation_type": "Skola",
        "organisation_code": "RIVENDELL",
        "parent_id": ORGS["middle_earth"],
        "municipality_code": "0180",
        "email": "info@rivendell.edu",
        "phone_number": "08-111 22 33",
        "url": "https://rivendell.edu",
        "street_address": "Imladris 42",
        "postal_code": "112 33",
        "locality": "Imladris",
    },
    {
        "id": ORGS["rivendell_grundskola"],
        "display_name": "Rivendell Grundskola",
        "organisation_type": "Skolenhet",
        "organisation_code": "RIVGR",
        "school_unit_code": "12345678",
        "school_types": "GR",
        "parent_id": ORGS["rivendell_academy"],
        "municipality_code": "0180",
        "email": "grundskola@rivendell.edu",
    },
    {
        "id": ORGS["rivendell_gymnasium"],
        "display_name": "Rivendell Gymnasium",
        "organisation_type": "Skolenhet",
        "organisation_code": "RIVGY",
        "school_unit_code": "12345679",
        "school_types": "GY",
        "parent_id": ORGS["rivendell_academy"],
        "municipality_code": "0180",
        "email": "gymnasium@rivendell.edu",
    },
]

# Staff members
STAFF = [
    {
        "id": PERSONS["gandalf"],
        "given_name": "Gandalf",
        "family_name": "the Grey",
        "email": "gandalf@rivendell.edu",
        "edu_person_principal_name": "gandalf@rivendell.edu",
        "birth_date": date(1000, 1, 1),
        "sex": "Man",
        "external_id": "STAFF001",
        "duty_role": "Rektor",
        "signature": "GAN",
        "description": "Headmaster and Wizard",
    },
    {
        "id": PERSONS["elrond"],
        "given_name": "Elrond",
        "family_name": "Half-elven",
        "email": "elrond@rivendell.edu",
        "edu_person_principal_name": "elrond@rivendell.edu",
        "birth_date": date(500, 6, 15),
        "sex": "Man",
        "external_id": "STAFF002",
        "duty_role": "Rektor",
        "signature": "ELR",
        "description": "Deputy Headmaster",
    },
    {
        "id": PERSONS["galadriel"],
        "given_name": "Galadriel",
        "family_name": "of Lothlórien",
        "email": "galadriel@rivendell.edu",
        "edu_person_principal_name": "galadriel@rivendell.edu",
        "birth_date": date(1, 1, 1),
        "sex": "Kvinna",
        "external_id": "STAFF003",
        "duty_role": "Lärare",
        "signature": "GAL",
        "description": "Arts & Foresight Teacher (EHT)",
    },
    {
        "id": PERSONS["celeborn"],
        "given_name": "Celeborn",
        "family_name": "the Wise",
        "email": "celeborn@rivendell.edu",
        "edu_person_principal_name": "celeborn@rivendell.edu",
        "birth_date": date(100, 3, 20),
        "sex": "Man",
        "external_id": "STAFF004",
        "duty_role": "Lärare",
        "signature": "CEL",
        "description": "History Teacher",
    },
    {
        "id": PERSONS["aragorn"],
        "given_name": "Aragorn",
        "family_name": "Elessar",
        "middle_name": "son of Arathorn",
        "email": "aragorn@rivendell.edu",
        "edu_person_principal_name": "aragorn@rivendell.edu",
        "birth_date": date(2931, 3, 1),
        "sex": "Man",
        "external_id": "STAFF005",
        "duty_role": "Lärare",
        "signature": "ARA",
        "description": "Survival Skills & Outdoor Education",
    },
    {
        "id": PERSONS["bilbo"],
        "given_name": "Bilbo",
        "family_name": "Baggins",
        "email": "bilbo@rivendell.edu",
        "edu_person_principal_name": "bilbo@rivendell.edu",
        "birth_date": date(2890, 9, 22),
        "sex": "Man",
        "external_id": "STAFF006",
        "duty_role": "Bibliotekarie",
        "signature": "BIL",
        "description": "Librarian and Frodo's Guardian",
        "street_address": "Bag End, Hobbiton",
        "postal_code": "111 11",
        "locality": "The Shire",
    },
    {
        "id": PERSONS["tom_bombadil"],
        "given_name": "Tom",
        "family_name": "Bombadil",
        "email": "tom@rivendell.edu",
        "birth_date": date(1, 1, 1),
        "sex": "Man",
        "external_id": "STAFF007",
        "duty_role": "Annan personal",
        "signature": "TOM",
        "description": "Groundskeeper",
    },
]

# Students
STUDENTS = [
    {
        "id": PERSONS["frodo"],
        "given_name": "Frodo",
        "family_name": "Baggins",
        "email": "frodo@student.rivendell.edu",
        "birth_date": date(2968, 9, 22),
        "sex": "Man",
        "external_id": "STU001",
        "civic_no": "20100922-1234",
        "guardian_ids": [PERSONS["bilbo"]],
        "group_id": GROUPS["4a_shire"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 4,
    },
    {
        "id": PERSONS["sam"],
        "given_name": "Samwise",
        "family_name": "Gamgee",
        "email": "sam@student.rivendell.edu",
        "birth_date": date(2980, 4, 6),
        "sex": "Man",
        "external_id": "STU002",
        "civic_no": "20110406-5678",
        "guardian_ids": [PERSONS["hamfast"]],
        "group_id": GROUPS["4a_shire"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 4,
    },
    {
        "id": PERSONS["merry"],
        "given_name": "Meriadoc",
        "family_name": "Brandybuck",
        "email": "merry@student.rivendell.edu",
        "birth_date": date(2982, 1, 1),
        "sex": "Man",
        "external_id": "STU003",
        "civic_no": "20120101-9012",
        "guardian_ids": [PERSONS["saradoc"]],
        "group_id": GROUPS["4b_buckland"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 4,
    },
    {
        "id": PERSONS["pippin"],
        "given_name": "Peregrin",
        "family_name": "Took",
        "email": "pippin@student.rivendell.edu",
        "birth_date": date(2990, 1, 1),
        "sex": "Man",
        "external_id": "STU004",
        "civic_no": "20130101-3456",
        "guardian_ids": [PERSONS["paladin"]],
        "group_id": GROUPS["4b_buckland"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 4,
    },
    {
        "id": PERSONS["faramir"],
        "given_name": "Faramir",
        "family_name": "of Gondor",
        "email": "faramir@student.rivendell.edu",
        "birth_date": date(2983, 1, 1),
        "sex": "Man",
        "external_id": "STU005",
        "civic_no": "20110601-7890",
        "guardian_ids": [PERSONS["denethor"]],
        "group_id": GROUPS["5a_gondor"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 5,
    },
    {
        "id": PERSONS["eowyn"],
        "given_name": "Éowyn",
        "family_name": "of Rohan",
        "email": "eowyn@student.rivendell.edu",
        "birth_date": date(2995, 1, 1),
        "sex": "Kvinna",
        "external_id": "STU006",
        "civic_no": "20100315-2345",
        "guardian_ids": [PERSONS["theoden"]],
        "group_id": GROUPS["5a_gondor"],
        "school_unit_id": ORGS["rivendell_grundskola"],
        "school_year": 5,
    },
    {
        "id": PERSONS["boromir"],
        "given_name": "Boromir",
        "family_name": "of Gondor",
        "email": "boromir@student.rivendell.edu",
        "birth_date": date(2978, 1, 1),
        "sex": "Man",
        "external_id": "STU007",
        "civic_no": "20080101-6789",
        "guardian_ids": [PERSONS["denethor"]],
        "group_id": GROUPS["gy1_fellowship"],
        "school_unit_id": ORGS["rivendell_gymnasium"],
        "school_year": 1,
    },
    {
        "id": PERSONS["eomer"],
        "given_name": "Éomer",
        "family_name": "of Rohan",
        "email": "eomer@student.rivendell.edu",
        "birth_date": date(2991, 1, 1),
        "sex": "Man",
        "external_id": "STU008",
        "civic_no": "20090701-0123",
        "guardian_ids": [PERSONS["theoden"]],
        "group_id": GROUPS["gy1_fellowship"],
        "school_unit_id": ORGS["rivendell_gymnasium"],
        "school_year": 1,
    },
    {
        "id": PERSONS["arwen"],
        "given_name": "Arwen",
        "family_name": "Undómiel",
        "email": "arwen@student.rivendell.edu",
        "birth_date": date(241, 1, 1),
        "sex": "Kvinna",
        "external_id": "STU009",
        "guardian_ids": [PERSONS["elrond"]],
        "group_id": GROUPS["gy2_elven"],
        "school_unit_id": ORGS["rivendell_gymnasium"],
        "school_year": 2,
    },
    {
        "id": PERSONS["legolas"],
        "given_name": "Legolas",
        "family_name": "Greenleaf",
        "email": "legolas@student.rivendell.edu",
        "birth_date": date(500, 1, 1),
        "sex": "Man",
        "external_id": "STU010",
        "guardian_ids": [PERSONS["thranduil"]],
        "group_id": GROUPS["gy2_elven"],
        "school_unit_id": ORGS["rivendell_gymnasium"],
        "school_year": 2,
    },
]

# Guardians (not staff)
GUARDIANS = [
    {
        "id": PERSONS["hamfast"],
        "given_name": "Hamfast",
        "family_name": "Gamgee",
        "email": "gaffer@shire.me",
        "birth_date": date(2926, 1, 1),
        "sex": "Man",
        "phone_number": "070-123 45 67",
        "street_address": "3 Bagshot Row, Hobbiton",
        "postal_code": "111 11",
        "locality": "The Shire",
        "external_id": "GUARD001",
        "civic_no": "19760415-1001",
    },
    {
        "id": PERSONS["saradoc"],
        "given_name": "Saradoc",
        "family_name": "Brandybuck",
        "email": "saradoc@buckland.me",
        "birth_date": date(2940, 1, 1),
        "sex": "Man",
        "phone_number": "070-234 56 78",
        "street_address": "Brandy Hall, Buckland",
        "postal_code": "111 22",
        "locality": "Buckland",
        "external_id": "GUARD002",
        "civic_no": "19780622-1002",
    },
    {
        "id": PERSONS["paladin"],
        "given_name": "Paladin",
        "family_name": "Took II",
        "email": "paladin@tookborough.me",
        "birth_date": date(2933, 1, 1),
        "sex": "Man",
        "phone_number": "070-345 67 89",
        "street_address": "Great Smials, Tuckborough",
        "postal_code": "111 33",
        "locality": "Tookland",
        "external_id": "GUARD003",
        "civic_no": "19750930-1003",
    },
    {
        "id": PERSONS["denethor"],
        "given_name": "Denethor II",
        "family_name": "of Gondor",
        "email": "denethor@gondor.gov",
        "birth_date": date(2930, 1, 1),
        "sex": "Man",
        "phone_number": "070-456 78 90",
        "street_address": "Citadel, Minas Tirith",
        "postal_code": "200 00",
        "locality": "Minas Tirith",
        "external_id": "GUARD004",
        "civic_no": "19721105-1004",
    },
    {
        "id": PERSONS["theoden"],
        "given_name": "Théoden",
        "family_name": "King of Rohan",
        "email": "theoden@rohan.gov",
        "birth_date": date(2948, 1, 1),
        "sex": "Man",
        "phone_number": "070-567 89 01",
        "street_address": "Meduseld, Edoras",
        "postal_code": "300 00",
        "locality": "Edoras",
        "external_id": "GUARD005",
        "civic_no": "19680318-1005",
    },
    {
        "id": PERSONS["thranduil"],
        "given_name": "Thranduil",
        "family_name": "Elvenking",
        "email": "thranduil@mirkwood.elf",
        "birth_date": date(1, 1, 1),
        "sex": "Man",
        "phone_number": "070-678 90 12",
        "street_address": "Halls of the Elvenking, Northern Mirkwood",
        "postal_code": "400 00",
        "locality": "Mirkwood",
        "external_id": "GUARD006",
        "civic_no": "19550101-1006",
    },
]

# Groups (classes)
GROUPS_DATA = [
    {
        "id": GROUPS["4a_shire"],
        "display_name": "Klass 4A - The Shire Class",
        "group_code": "4A",
        "group_type": "Klass",
        "school_type": "GR",
        "organisation_id": ORGS["rivendell_grundskola"],
        "start_date": date(2024, 8, 15),
        "mentor_id": PERSONS["aragorn"],  # Aragorn is mentor
    },
    {
        "id": GROUPS["4b_buckland"],
        "display_name": "Klass 4B - Buckland Class",
        "group_code": "4B",
        "group_type": "Klass",
        "school_type": "GR",
        "organisation_id": ORGS["rivendell_grundskola"],
        "start_date": date(2024, 8, 15),
        "mentor_id": PERSONS["celeborn"],
    },
    {
        "id": GROUPS["5a_gondor"],
        "display_name": "Klass 5A - Gondor Class",
        "group_code": "5A",
        "group_type": "Klass",
        "school_type": "GR",
        "organisation_id": ORGS["rivendell_grundskola"],
        "start_date": date(2024, 8, 15),
        "mentor_id": PERSONS["galadriel"],
    },
    {
        "id": GROUPS["gy1_fellowship"],
        "display_name": "Klass GY1 - Fellowship",
        "group_code": "GY1",
        "group_type": "Klass",
        "school_type": "GY",
        "organisation_id": ORGS["rivendell_gymnasium"],
        "start_date": date(2024, 8, 15),
        "mentor_id": PERSONS["gandalf"],
    },
    {
        "id": GROUPS["gy2_elven"],
        "display_name": "Klass GY2 - Elven Studies",
        "group_code": "GY2",
        "group_type": "Klass",
        "school_type": "GY",
        "organisation_id": ORGS["rivendell_gymnasium"],
        "start_date": date(2024, 8, 15),
        "mentor_id": PERSONS["elrond"],
    },
]
