"""
Lord of the Rings themed demo data for Fake SIS.
Massively expanded: 62 students, 17 staff, teaching groups, activities.
"""
from datetime import date
from uuid import uuid4

# Fixed UUIDs for consistent data
ORGS = {
    "middle_earth": str(uuid4()),
    "rivendell_academy": str(uuid4()),
    "rivendell_grundskola": str(uuid4()),
    "rivendell_gymnasium": str(uuid4()),
}

# Generate UUIDs for all persons
def _gen_ids(*names):
    return {name: str(uuid4()) for name in names}

PERSONS = _gen_ids(
    # Staff (17)
    "gandalf", "saruman", "elrond", "galadriel", "celeborn", "aragorn",
    "faramir_staff", "eowyn_staff", "gimli", "glorfindel", "cirdan",
    "radagast", "beorn", "treebeard", "haldir", "bilbo", "tom_bombadil",
    # Students - Hobbits (20)
    "frodo", "sam", "merry", "pippin", "rosie", "diamond", "estella",
    "fatty", "folco", "lotho", "pearl", "pimpernel", "pervinca",
    "marigold", "hamson", "halfred", "daisy", "may", "robin", "nibs",
    # Students - Elves (12)
    "arwen", "legolas", "elladan", "elrohir", "lindir", "figwit",
    "rumil", "orophin", "gildor", "nimrodel", "amroth", "celebrian",
    # Students - Men (20)
    "boromir", "eomer", "theodred", "erkenbrand", "grimbold", "elfhelm",
    "imrahil", "beregond", "bergil", "ioreth", "dervorin", "duinhir",
    "golasgil", "hirluin", "forlong", "angbor", "malbeth", "halbarad",
    "elladan_dunedain", "arathorn",
    # Students - Dwarves (10)
    "thorin_jr", "dain_jr", "fili_jr", "kili_jr", "balin_jr", "dwalin_jr",
    "ori_jr", "nori_jr", "dori_jr", "bifur_jr",
    # Guardians (25)
    "hamfast", "saradoc", "paladin", "denethor", "theoden", "thranduil",
    "erestor", "lindir_guardian", "gloin", "oin", "bombur", "bofur",
    "esmeralda", "eglantine", "finduilas", "morwen", "idril", "cirion",
    "thorin_sr", "dain_sr", "fili_sr", "kili_sr", "balin_sr", "nain", "fundin",
)

# Class groups (homerooms) - 11 classes
GROUPS = _gen_ids(
    # Grundskola
    "4a_shire", "4b_buckland", "5a_gondor", "5b_rohan", "6a_rivendell",
    "6b_mirkwood", "7a_erebor",
    # Gymnasium
    "gy1_fellowship", "gy2_elven", "gy3_dunedain", "gy3_khazad",
)

# Teaching groups (Undervisning) - subject groups
TEACHING_GROUPS = _gen_ids(
    # Swedish (Svenska)
    "sv_4a", "sv_4b", "sv_5ab", "sv_6ab", "sv_7a", "sv_gy1", "sv_gy2", "sv_gy3",
    # Math (Matematik)
    "ma_4a", "ma_4b", "ma_5ab", "ma_6ab", "ma_7a", "ma_gy1", "ma_gy2", "ma_gy3",
    # English (Engelska)
    "en_4a", "en_4b", "en_5ab", "en_6ab", "en_7a", "en_gy1", "en_gy2", "en_gy3",
    # History (Historia)
    "hi_5ab", "hi_6ab", "hi_7a", "hi_gy1", "hi_gy2", "hi_gy3",
    # Nature (NO)
    "no_4ab", "no_5ab", "no_6ab", "no_7a", "no_gy1", "no_gy2", "no_gy3",
    # PE (Idrott)
    "id_4ab", "id_5ab", "id_6ab", "id_7a", "id_gy1", "id_gy23",
    # Art/Music
    "bl_4ab", "bl_5ab", "bl_6ab", "mu_4ab", "mu_5ab", "mu_6ab",
)

ACTIVITIES = _gen_ids(
    # Activities for each teaching group
    "act_sv_4a", "act_sv_4b", "act_sv_5ab", "act_sv_6ab", "act_sv_7a",
    "act_sv_gy1", "act_sv_gy2", "act_sv_gy3",
    "act_ma_4a", "act_ma_4b", "act_ma_5ab", "act_ma_6ab", "act_ma_7a",
    "act_ma_gy1", "act_ma_gy2", "act_ma_gy3",
    "act_en_4a", "act_en_4b", "act_en_5ab", "act_en_6ab", "act_en_7a",
    "act_en_gy1", "act_en_gy2", "act_en_gy3",
    "act_hi_5ab", "act_hi_6ab", "act_hi_7a", "act_hi_gy1", "act_hi_gy2", "act_hi_gy3",
    "act_no_4ab", "act_no_5ab", "act_no_6ab", "act_no_7a",
    "act_no_gy1", "act_no_gy2", "act_no_gy3",
    "act_id_4ab", "act_id_5ab", "act_id_6ab", "act_id_7a", "act_id_gy1", "act_id_gy23",
    "act_bl_4ab", "act_bl_5ab", "act_bl_6ab",
    "act_mu_4ab", "act_mu_5ab", "act_mu_6ab",
)

# Organisation hierarchy
ORGANISATIONS = [
    {
        "id": ORGS["middle_earth"],
        "display_name": "Middle-earth Educational Authority",
        "organisation_type": "Huvudman",
        "organisation_number": "802100-1234",
        "municipality_code": "0180",
        "email": "info@middle-earth.edu",
        "phone_number": "08-123 45 67",
        "url": "https://middle-earth.edu",
        "street_address": "Valinor väg 1",
        "postal_code": "111 22",
        "locality": "Aman",
    },
    {
        "id": ORGS["rivendell_academy"],
        "display_name": "Rivendell Academy",
        "organisation_type": "Skola",
        "organisation_code": "RIVENDELL",
        "parent_id": ORGS["middle_earth"],
        "municipality_code": "0180",
        "email": "info@rivendell.edu",
        "phone_number": "08-111 22 33",
        "url": "https://rivendell.edu",
        "street_address": "Imladris 42",
        "postal_code": "112 33",
        "locality": "Imladris",
    },
    {
        "id": ORGS["rivendell_grundskola"],
        "display_name": "Rivendell Grundskola",
        "organisation_type": "Skolenhet",
        "organisation_code": "RIVGR",
        "school_unit_code": "12345678",
        "school_types": "GR",
        "parent_id": ORGS["rivendell_academy"],
        "municipality_code": "0180",
        "email": "grundskola@rivendell.edu",
    },
    {
        "id": ORGS["rivendell_gymnasium"],
        "display_name": "Rivendell Gymnasium",
        "organisation_type": "Skolenhet",
        "organisation_code": "RIVGY",
        "school_unit_code": "12345679",
        "school_types": "GY",
        "parent_id": ORGS["rivendell_academy"],
        "municipality_code": "0180",
        "email": "gymnasium@rivendell.edu",
    },
]

# Staff members (17)
STAFF = [
    {"id": PERSONS["gandalf"], "given_name": "Gandalf", "family_name": "the Grey",
     "email": "gandalf@rivendell.edu", "duty_role": "Rektor", "signature": "GAN",
     "description": "Headmaster and Wizard", "sex": "Man", "external_id": "STAFF001"},
    {"id": PERSONS["saruman"], "given_name": "Saruman", "family_name": "the White",
     "email": "saruman@rivendell.edu", "duty_role": "Biträdande rektor", "signature": "SAR",
     "description": "Deputy Headmaster", "sex": "Man", "external_id": "STAFF002"},
    {"id": PERSONS["elrond"], "given_name": "Elrond", "family_name": "Half-elven",
     "email": "elrond@rivendell.edu", "duty_role": "Lärare", "signature": "ELR",
     "description": "Languages & Lore", "sex": "Man", "external_id": "STAFF003"},
    {"id": PERSONS["galadriel"], "given_name": "Galadriel", "family_name": "of Lothlórien",
     "email": "galadriel@rivendell.edu", "duty_role": "Lärare", "signature": "GAL",
     "description": "Arts & Foresight (EHT)", "sex": "Kvinna", "external_id": "STAFF004"},
    {"id": PERSONS["celeborn"], "given_name": "Celeborn", "family_name": "the Wise",
     "email": "celeborn@rivendell.edu", "duty_role": "Lärare", "signature": "CEL",
     "description": "History Teacher", "sex": "Man", "external_id": "STAFF005"},
    {"id": PERSONS["aragorn"], "given_name": "Aragorn", "family_name": "Elessar",
     "email": "aragorn@rivendell.edu", "duty_role": "Lärare", "signature": "ARA",
     "description": "Survival & PE", "sex": "Man", "external_id": "STAFF006"},
    {"id": PERSONS["faramir_staff"], "given_name": "Faramir", "family_name": "of Ithilien",
     "email": "faramir.teacher@rivendell.edu", "duty_role": "Lärare", "signature": "FAR",
     "description": "Swedish & Literature", "sex": "Man", "external_id": "STAFF007"},
    {"id": PERSONS["eowyn_staff"], "given_name": "Éowyn", "family_name": "of Rohan",
     "email": "eowyn.teacher@rivendell.edu", "duty_role": "Lärare", "signature": "EOW",
     "description": "English & PE", "sex": "Kvinna", "external_id": "STAFF008"},
    {"id": PERSONS["gimli"], "given_name": "Gimli", "family_name": "son of Glóin",
     "email": "gimli@rivendell.edu", "duty_role": "Lärare", "signature": "GIM",
     "description": "Math & Crafts", "sex": "Man", "external_id": "STAFF009"},
    {"id": PERSONS["glorfindel"], "given_name": "Glorfindel", "family_name": "of Rivendell",
     "email": "glorfindel@rivendell.edu", "duty_role": "Lärare", "signature": "GLO",
     "description": "Music & Languages", "sex": "Man", "external_id": "STAFF010"},
    {"id": PERSONS["cirdan"], "given_name": "Círdan", "family_name": "the Shipwright",
     "email": "cirdan@rivendell.edu", "duty_role": "Lärare", "signature": "CIR",
     "description": "Science & Technology", "sex": "Man", "external_id": "STAFF011"},
    {"id": PERSONS["radagast"], "given_name": "Radagast", "family_name": "the Brown",
     "email": "radagast@rivendell.edu", "duty_role": "Lärare", "signature": "RAD",
     "description": "Nature & Biology", "sex": "Man", "external_id": "STAFF012"},
    {"id": PERSONS["beorn"], "given_name": "Beorn", "family_name": "the Skinchanger",
     "email": "beorn@rivendell.edu", "duty_role": "Lärare", "signature": "BEO",
     "description": "PE & Outdoor Education", "sex": "Man", "external_id": "STAFF013"},
    {"id": PERSONS["treebeard"], "given_name": "Treebeard", "family_name": "Fangorn",
     "email": "treebeard@rivendell.edu", "duty_role": "Kurator", "signature": "TRE",
     "description": "School Counselor (EHT)", "sex": "Man", "external_id": "STAFF014"},
    {"id": PERSONS["haldir"], "given_name": "Haldir", "family_name": "of Lórien",
     "email": "haldir@rivendell.edu", "duty_role": "Specialpedagog", "signature": "HAL",
     "description": "Special Education (EHT)", "sex": "Man", "external_id": "STAFF015"},
    {"id": PERSONS["bilbo"], "given_name": "Bilbo", "family_name": "Baggins",
     "email": "bilbo@rivendell.edu", "duty_role": "Bibliotekarie", "signature": "BIL",
     "description": "Librarian", "sex": "Man", "external_id": "STAFF016"},
    {"id": PERSONS["tom_bombadil"], "given_name": "Tom", "family_name": "Bombadil",
     "email": "tom@rivendell.edu", "duty_role": "Annan personal", "signature": "TOM",
     "description": "Groundskeeper", "sex": "Man", "external_id": "STAFF017"},
]

# Students - Part 1: Hobbits (20)
STUDENTS_HOBBITS = [
    {"id": PERSONS["frodo"], "given_name": "Frodo", "family_name": "Baggins",
     "guardian_ids": [PERSONS["bilbo"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "civic_no": "20100922-1234", "sex": "Man", "external_id": "STU001"},
    {"id": PERSONS["sam"], "given_name": "Samwise", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "civic_no": "20110406-5678", "sex": "Man", "external_id": "STU002"},
    {"id": PERSONS["merry"], "given_name": "Meriadoc", "family_name": "Brandybuck",
     "guardian_ids": [PERSONS["saradoc"], PERSONS["esmeralda"]], "group_id": GROUPS["4b_buckland"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "civic_no": "20120101-9012", "sex": "Man", "external_id": "STU003"},
    {"id": PERSONS["pippin"], "given_name": "Peregrin", "family_name": "Took",
     "guardian_ids": [PERSONS["paladin"], PERSONS["eglantine"]], "group_id": GROUPS["4b_buckland"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "civic_no": "20130101-3456", "sex": "Man", "external_id": "STU004"},
    {"id": PERSONS["rosie"], "given_name": "Rosie", "family_name": "Cotton",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "civic_no": "20100515-1111", "sex": "Kvinna", "external_id": "STU005"},
    {"id": PERSONS["diamond"], "given_name": "Diamond", "family_name": "Took",
     "guardian_ids": [PERSONS["paladin"]], "group_id": GROUPS["5a_gondor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "civic_no": "20090815-2222", "sex": "Kvinna", "external_id": "STU006"},
    {"id": PERSONS["estella"], "given_name": "Estella", "family_name": "Bolger",
     "guardian_ids": [PERSONS["saradoc"]], "group_id": GROUPS["5a_gondor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "civic_no": "20091020-3333", "sex": "Kvinna", "external_id": "STU007"},
    {"id": PERSONS["fatty"], "given_name": "Fredegar", "family_name": "Bolger",
     "guardian_ids": [PERSONS["saradoc"]], "group_id": GROUPS["5b_rohan"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "civic_no": "20090305-4444", "sex": "Man", "external_id": "STU008"},
    {"id": PERSONS["folco"], "given_name": "Folco", "family_name": "Boffin",
     "guardian_ids": [PERSONS["paladin"]], "group_id": GROUPS["5b_rohan"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "civic_no": "20090612-5555", "sex": "Man", "external_id": "STU009"},
    {"id": PERSONS["lotho"], "given_name": "Lotho", "family_name": "Sackville-Baggins",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["6a_rivendell"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "civic_no": "20080122-6666", "sex": "Man", "external_id": "STU010"},
    {"id": PERSONS["pearl"], "given_name": "Pearl", "family_name": "Took",
     "guardian_ids": [PERSONS["paladin"]], "group_id": GROUPS["6a_rivendell"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "civic_no": "20080415-7777", "sex": "Kvinna", "external_id": "STU011"},
    {"id": PERSONS["pimpernel"], "given_name": "Pimpernel", "family_name": "Took",
     "guardian_ids": [PERSONS["paladin"]], "group_id": GROUPS["6b_mirkwood"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "civic_no": "20080720-8888", "sex": "Kvinna", "external_id": "STU012"},
    {"id": PERSONS["pervinca"], "given_name": "Pervinca", "family_name": "Took",
     "guardian_ids": [PERSONS["paladin"]], "group_id": GROUPS["6b_mirkwood"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "civic_no": "20080903-9999", "sex": "Kvinna", "external_id": "STU013"},
    {"id": PERSONS["marigold"], "given_name": "Marigold", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "civic_no": "20070215-1010", "sex": "Kvinna", "external_id": "STU014"},
    {"id": PERSONS["hamson"], "given_name": "Hamson", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "civic_no": "20070530-1111", "sex": "Man", "external_id": "STU015"},
    {"id": PERSONS["halfred"], "given_name": "Halfred", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "civic_no": "20060810-1212", "sex": "Man", "external_id": "STU016"},
    {"id": PERSONS["daisy"], "given_name": "Daisy", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "civic_no": "20061115-1313", "sex": "Kvinna", "external_id": "STU017"},
    {"id": PERSONS["may"], "given_name": "May", "family_name": "Gamgee",
     "guardian_ids": [PERSONS["hamfast"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "civic_no": "20050320-1414", "sex": "Kvinna", "external_id": "STU018"},
    {"id": PERSONS["robin"], "given_name": "Robin", "family_name": "Smallburrow",
     "guardian_ids": [PERSONS["saradoc"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "civic_no": "20050625-1515", "sex": "Man", "external_id": "STU019"},
    {"id": PERSONS["nibs"], "given_name": "Nibs", "family_name": "Cotton",
     "guardian_ids": [PERSONS["saradoc"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "civic_no": "20040905-1616", "sex": "Man", "external_id": "STU020"},
]

# Students - Part 2: Elves (12)
STUDENTS_ELVES = [
    {"id": PERSONS["arwen"], "given_name": "Arwen", "family_name": "Undómiel",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Kvinna", "external_id": "STU021"},
    {"id": PERSONS["legolas"], "given_name": "Legolas", "family_name": "Greenleaf",
     "guardian_ids": [PERSONS["thranduil"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Man", "external_id": "STU022"},
    {"id": PERSONS["elladan"], "given_name": "Elladan", "family_name": "of Rivendell",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU023"},
    {"id": PERSONS["elrohir"], "given_name": "Elrohir", "family_name": "of Rivendell",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU024"},
    {"id": PERSONS["lindir"], "given_name": "Lindir", "family_name": "the Minstrel",
     "guardian_ids": [PERSONS["lindir_guardian"]], "group_id": GROUPS["6a_rivendell"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU025"},
    {"id": PERSONS["figwit"], "given_name": "Figwit", "family_name": "of Rivendell",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["6a_rivendell"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU026"},
    {"id": PERSONS["rumil"], "given_name": "Rúmil", "family_name": "of Lórien",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["5a_gondor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU027"},
    {"id": PERSONS["orophin"], "given_name": "Orophin", "family_name": "of Lórien",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["5b_rohan"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU028"},
    {"id": PERSONS["gildor"], "given_name": "Gildor", "family_name": "Inglorion",
     "guardian_ids": [PERSONS["lindir_guardian"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "sex": "Man", "external_id": "STU029"},
    {"id": PERSONS["nimrodel"], "given_name": "Nimrodel", "family_name": "of Lórien",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Kvinna", "external_id": "STU030"},
    {"id": PERSONS["amroth"], "given_name": "Amroth", "family_name": "of Lórien",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["4b_buckland"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Man", "external_id": "STU031"},
    {"id": PERSONS["celebrian"], "given_name": "Celebrían", "family_name": "of Lórien",
     "guardian_ids": [PERSONS["erestor"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "sex": "Kvinna", "external_id": "STU032"},
]

# Students - Part 3: Men (20)
STUDENTS_MEN = [
    {"id": PERSONS["boromir"], "given_name": "Boromir", "family_name": "of Gondor",
     "guardian_ids": [PERSONS["denethor"], PERSONS["finduilas"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "civic_no": "20080101-6789", "sex": "Man", "external_id": "STU033"},
    {"id": PERSONS["eomer"], "given_name": "Éomer", "family_name": "of Rohan",
     "guardian_ids": [PERSONS["theoden"], PERSONS["morwen"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "civic_no": "20090701-0123", "sex": "Man", "external_id": "STU034"},
    {"id": PERSONS["theodred"], "given_name": "Théodred", "family_name": "of Rohan",
     "guardian_ids": [PERSONS["theoden"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Man", "external_id": "STU035"},
    {"id": PERSONS["erkenbrand"], "given_name": "Erkenbrand", "family_name": "of Westfold",
     "guardian_ids": [PERSONS["theoden"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU036"},
    {"id": PERSONS["grimbold"], "given_name": "Grimbold", "family_name": "of Grimslade",
     "guardian_ids": [PERSONS["theoden"]], "group_id": GROUPS["gy3_khazad"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU037"},
    {"id": PERSONS["elfhelm"], "given_name": "Elfhelm", "family_name": "Marshal",
     "guardian_ids": [PERSONS["morwen"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "sex": "Man", "external_id": "STU038"},
    {"id": PERSONS["imrahil"], "given_name": "Imrahil", "family_name": "of Dol Amroth",
     "guardian_ids": [PERSONS["denethor"]], "group_id": GROUPS["6b_mirkwood"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU039"},
    {"id": PERSONS["beregond"], "given_name": "Beregond", "family_name": "of the Guard",
     "guardian_ids": [PERSONS["denethor"]], "group_id": GROUPS["5a_gondor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU040"},
    {"id": PERSONS["bergil"], "given_name": "Bergil", "family_name": "son of Beregond",
     "guardian_ids": [PERSONS["denethor"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Man", "external_id": "STU041"},
    {"id": PERSONS["ioreth"], "given_name": "Ioreth", "family_name": "of the Houses",
     "guardian_ids": [PERSONS["finduilas"]], "group_id": GROUPS["4b_buckland"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Kvinna", "external_id": "STU042"},
    {"id": PERSONS["dervorin"], "given_name": "Dervorin", "family_name": "of Ringló Vale",
     "guardian_ids": [PERSONS["cirion"]], "group_id": GROUPS["5b_rohan"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU043"},
    {"id": PERSONS["duinhir"], "given_name": "Duinhir", "family_name": "of Blackroot",
     "guardian_ids": [PERSONS["cirion"]], "group_id": GROUPS["5b_rohan"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU044"},
    {"id": PERSONS["golasgil"], "given_name": "Golasgil", "family_name": "of Anfalas",
     "guardian_ids": [PERSONS["cirion"]], "group_id": GROUPS["6a_rivendell"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU045"},
    {"id": PERSONS["hirluin"], "given_name": "Hirluin", "family_name": "the Fair",
     "guardian_ids": [PERSONS["finduilas"]], "group_id": GROUPS["6b_mirkwood"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU046"},
    {"id": PERSONS["forlong"], "given_name": "Forlong", "family_name": "the Fat",
     "guardian_ids": [PERSONS["denethor"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "sex": "Man", "external_id": "STU047"},
    {"id": PERSONS["angbor"], "given_name": "Angbor", "family_name": "of Lamedon",
     "guardian_ids": [PERSONS["cirion"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "sex": "Man", "external_id": "STU048"},
    {"id": PERSONS["malbeth"], "given_name": "Malbeth", "family_name": "the Seer",
     "guardian_ids": [PERSONS["idril"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Man", "external_id": "STU049"},
    {"id": PERSONS["halbarad"], "given_name": "Halbarad", "family_name": "Dúnadan",
     "guardian_ids": [PERSONS["idril"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU050"},
    {"id": PERSONS["elladan_dunedain"], "given_name": "Arahad", "family_name": "of the North",
     "guardian_ids": [PERSONS["idril"]], "group_id": GROUPS["gy3_dunedain"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU051"},
    {"id": PERSONS["arathorn"], "given_name": "Arathorn", "family_name": "the Younger",
     "guardian_ids": [PERSONS["idril"]], "group_id": GROUPS["gy3_khazad"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU052"},
]

# Students - Part 4: Dwarves (10)
STUDENTS_DWARVES = [
    {"id": PERSONS["thorin_jr"], "given_name": "Thorin III", "family_name": "Stonehelm",
     "guardian_ids": [PERSONS["thorin_sr"], PERSONS["fundin"]], "group_id": GROUPS["gy3_khazad"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU053"},
    {"id": PERSONS["dain_jr"], "given_name": "Dáin III", "family_name": "Ironfoot",
     "guardian_ids": [PERSONS["dain_sr"]], "group_id": GROUPS["gy3_khazad"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 3,
     "sex": "Man", "external_id": "STU054"},
    {"id": PERSONS["fili_jr"], "given_name": "Fíli", "family_name": "son of Víli",
     "guardian_ids": [PERSONS["fili_sr"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Man", "external_id": "STU055"},
    {"id": PERSONS["kili_jr"], "given_name": "Kíli", "family_name": "son of Víli",
     "guardian_ids": [PERSONS["kili_sr"]], "group_id": GROUPS["gy2_elven"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 2,
     "sex": "Man", "external_id": "STU056"},
    {"id": PERSONS["balin_jr"], "given_name": "Bálin", "family_name": "of Erebor",
     "guardian_ids": [PERSONS["balin_sr"]], "group_id": GROUPS["gy1_fellowship"],
     "school_unit_id": ORGS["rivendell_gymnasium"], "school_year": 1,
     "sex": "Man", "external_id": "STU057"},
    {"id": PERSONS["dwalin_jr"], "given_name": "Dwalin", "family_name": "of Erebor",
     "guardian_ids": [PERSONS["fundin"]], "group_id": GROUPS["7a_erebor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 7,
     "sex": "Man", "external_id": "STU058"},
    {"id": PERSONS["ori_jr"], "given_name": "Ori", "family_name": "the Scribe",
     "guardian_ids": [PERSONS["nain"]], "group_id": GROUPS["6b_mirkwood"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 6,
     "sex": "Man", "external_id": "STU059"},
    {"id": PERSONS["nori_jr"], "given_name": "Nori", "family_name": "of Erebor",
     "guardian_ids": [PERSONS["nain"]], "group_id": GROUPS["5a_gondor"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 5,
     "sex": "Man", "external_id": "STU060"},
    {"id": PERSONS["dori_jr"], "given_name": "Dori", "family_name": "of Erebor",
     "guardian_ids": [PERSONS["nain"]], "group_id": GROUPS["4a_shire"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Man", "external_id": "STU061"},
    {"id": PERSONS["bifur_jr"], "given_name": "Bifur", "family_name": "of the Blue Mountains",
     "guardian_ids": [PERSONS["gloin"]], "group_id": GROUPS["4b_buckland"],
     "school_unit_id": ORGS["rivendell_grundskola"], "school_year": 4,
     "sex": "Man", "external_id": "STU062"},
]

# Combine all students
STUDENTS = STUDENTS_HOBBITS + STUDENTS_ELVES + STUDENTS_MEN + STUDENTS_DWARVES

# Add email and birth_date to all students
for i, s in enumerate(STUDENTS):
    if "email" not in s:
        s["email"] = f"{s['given_name'].lower()}@student.rivendell.edu"
    if "birth_date" not in s:
        s["birth_date"] = date(2010 - s["school_year"], 6, 15)

# Guardians (25)
GUARDIANS = [
    {"id": PERSONS["hamfast"], "given_name": "Hamfast", "family_name": "Gamgee",
     "email": "gaffer@shire.me", "phone_number": "070-123 45 67", "external_id": "GUARD001",
     "street_address": "3 Bagshot Row, Hobbiton", "locality": "The Shire", "sex": "Man"},
    {"id": PERSONS["saradoc"], "given_name": "Saradoc", "family_name": "Brandybuck",
     "email": "saradoc@buckland.me", "phone_number": "070-234 56 78", "external_id": "GUARD002",
     "street_address": "Brandy Hall, Buckland", "locality": "Buckland", "sex": "Man"},
    {"id": PERSONS["paladin"], "given_name": "Paladin", "family_name": "Took II",
     "email": "paladin@tookborough.me", "phone_number": "070-345 67 89", "external_id": "GUARD003",
     "street_address": "Great Smials, Tuckborough", "locality": "Tookland", "sex": "Man"},
    {"id": PERSONS["denethor"], "given_name": "Denethor II", "family_name": "of Gondor",
     "email": "denethor@gondor.gov", "phone_number": "070-456 78 90", "external_id": "GUARD004",
     "street_address": "Citadel, Minas Tirith", "locality": "Minas Tirith", "sex": "Man"},
    {"id": PERSONS["theoden"], "given_name": "Théoden", "family_name": "King of Rohan",
     "email": "theoden@rohan.gov", "phone_number": "070-567 89 01", "external_id": "GUARD005",
     "street_address": "Meduseld, Edoras", "locality": "Edoras", "sex": "Man"},
    {"id": PERSONS["thranduil"], "given_name": "Thranduil", "family_name": "Elvenking",
     "email": "thranduil@mirkwood.elf", "phone_number": "070-678 90 12", "external_id": "GUARD006",
     "street_address": "Halls of the Elvenking", "locality": "Mirkwood", "sex": "Man"},
    {"id": PERSONS["erestor"], "given_name": "Erestor", "family_name": "of Rivendell",
     "email": "erestor@rivendell.elf", "phone_number": "070-789 01 23", "external_id": "GUARD007",
     "street_address": "House of Elrond", "locality": "Rivendell", "sex": "Man"},
    {"id": PERSONS["lindir_guardian"], "given_name": "Galdor", "family_name": "of the Havens",
     "email": "galdor@havens.elf", "phone_number": "070-890 12 34", "external_id": "GUARD008",
     "street_address": "Grey Havens", "locality": "Mithlond", "sex": "Man"},
    {"id": PERSONS["gloin"], "given_name": "Glóin", "family_name": "of Erebor",
     "email": "gloin@erebor.dwarf", "phone_number": "070-901 23 45", "external_id": "GUARD009",
     "street_address": "Erebor, Gate Hall", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["esmeralda"], "given_name": "Esmeralda", "family_name": "Brandybuck",
     "email": "esmeralda@buckland.me", "phone_number": "070-012 34 56", "external_id": "GUARD010",
     "street_address": "Brandy Hall", "locality": "Buckland", "sex": "Kvinna"},
    {"id": PERSONS["eglantine"], "given_name": "Eglantine", "family_name": "Took",
     "email": "eglantine@tookborough.me", "phone_number": "070-123 45 00", "external_id": "GUARD011",
     "street_address": "Great Smials", "locality": "Tookland", "sex": "Kvinna"},
    {"id": PERSONS["finduilas"], "given_name": "Finduilas", "family_name": "of Dol Amroth",
     "email": "finduilas@gondor.gov", "phone_number": "070-234 56 00", "external_id": "GUARD012",
     "street_address": "Citadel", "locality": "Minas Tirith", "sex": "Kvinna"},
    {"id": PERSONS["morwen"], "given_name": "Morwen", "family_name": "Steelsheen",
     "email": "morwen@rohan.gov", "phone_number": "070-345 67 00", "external_id": "GUARD013",
     "street_address": "Meduseld", "locality": "Edoras", "sex": "Kvinna"},
    {"id": PERSONS["idril"], "given_name": "Ivorwen", "family_name": "of the Dúnedain",
     "email": "ivorwen@dunedain.north", "phone_number": "070-456 78 00", "external_id": "GUARD014",
     "street_address": "Ranger Camp", "locality": "Eriador", "sex": "Kvinna"},
    {"id": PERSONS["cirion"], "given_name": "Cirion", "family_name": "of Gondor",
     "email": "cirion@gondor.gov", "phone_number": "070-567 89 00", "external_id": "GUARD015",
     "street_address": "White Tower", "locality": "Minas Tirith", "sex": "Man"},
    {"id": PERSONS["thorin_sr"], "given_name": "Thorin II", "family_name": "Oakenshield",
     "email": "thorin@erebor.dwarf", "phone_number": "070-678 90 00", "external_id": "GUARD016",
     "street_address": "Throne Room", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["dain_sr"], "given_name": "Dáin II", "family_name": "Ironfoot",
     "email": "dain@ironhills.dwarf", "phone_number": "070-789 01 00", "external_id": "GUARD017",
     "street_address": "Iron Hills", "locality": "Iron Hills", "sex": "Man"},
    {"id": PERSONS["fili_sr"], "given_name": "Víli", "family_name": "of Durin's Folk",
     "email": "vili@erebor.dwarf", "phone_number": "070-890 12 00", "external_id": "GUARD018",
     "street_address": "Erebor", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["kili_sr"], "given_name": "Dís", "family_name": "of Durin's Folk",
     "email": "dis@erebor.dwarf", "phone_number": "070-901 23 00", "external_id": "GUARD019",
     "street_address": "Erebor", "locality": "Erebor", "sex": "Kvinna"},
    {"id": PERSONS["balin_sr"], "given_name": "Fundin", "family_name": "the Elder",
     "email": "fundin.elder@erebor.dwarf", "phone_number": "070-012 34 00", "external_id": "GUARD020",
     "street_address": "Erebor", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["nain"], "given_name": "Náin", "family_name": "of Erebor",
     "email": "nain@erebor.dwarf", "phone_number": "070-111 22 33", "external_id": "GUARD021",
     "street_address": "Erebor", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["fundin"], "given_name": "Fundin", "family_name": "the Younger",
     "email": "fundin@erebor.dwarf", "phone_number": "070-222 33 44", "external_id": "GUARD022",
     "street_address": "Erebor", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["oin"], "given_name": "Óin", "family_name": "the Healer",
     "email": "oin@erebor.dwarf", "phone_number": "070-333 44 55", "external_id": "GUARD023",
     "street_address": "Healing Halls", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["bombur"], "given_name": "Bombur", "family_name": "the Rotund",
     "email": "bombur@erebor.dwarf", "phone_number": "070-444 55 66", "external_id": "GUARD024",
     "street_address": "Great Hall", "locality": "Erebor", "sex": "Man"},
    {"id": PERSONS["bofur"], "given_name": "Bofur", "family_name": "the Miner",
     "email": "bofur@erebor.dwarf", "phone_number": "070-555 66 77", "external_id": "GUARD025",
     "street_address": "Mine Entrance", "locality": "Erebor", "sex": "Man"},
]

# Class groups (homerooms) - 11 classes
GROUPS_DATA = [
    {"id": GROUPS["4a_shire"], "display_name": "Klass 4A - Shire", "group_code": "4A",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["aragorn"]},
    {"id": GROUPS["4b_buckland"], "display_name": "Klass 4B - Buckland", "group_code": "4B",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["celeborn"]},
    {"id": GROUPS["5a_gondor"], "display_name": "Klass 5A - Gondor", "group_code": "5A",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["galadriel"]},
    {"id": GROUPS["5b_rohan"], "display_name": "Klass 5B - Rohan", "group_code": "5B",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["eowyn_staff"]},
    {"id": GROUPS["6a_rivendell"], "display_name": "Klass 6A - Rivendell", "group_code": "6A",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["elrond"]},
    {"id": GROUPS["6b_mirkwood"], "display_name": "Klass 6B - Mirkwood", "group_code": "6B",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["radagast"]},
    {"id": GROUPS["7a_erebor"], "display_name": "Klass 7A - Erebor", "group_code": "7A",
     "group_type": "Klass", "school_type": "GR", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["gimli"]},
    {"id": GROUPS["gy1_fellowship"], "display_name": "GY1 - Fellowship", "group_code": "GY1",
     "group_type": "Klass", "school_type": "GY", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["gandalf"]},
    {"id": GROUPS["gy2_elven"], "display_name": "GY2 - Elven Studies", "group_code": "GY2",
     "group_type": "Klass", "school_type": "GY", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["glorfindel"]},
    {"id": GROUPS["gy3_dunedain"], "display_name": "GY3A - Dúnedain", "group_code": "GY3A",
     "group_type": "Klass", "school_type": "GY", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["faramir_staff"]},
    {"id": GROUPS["gy3_khazad"], "display_name": "GY3B - Khazad-dûm", "group_code": "GY3B",
     "group_type": "Klass", "school_type": "GY", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "mentor_id": PERSONS["cirdan"]},
]

# Teaching groups (Undervisning) - subject groups
TEACHING_GROUPS_DATA = [
    # Swedish - Faramir teaches
    {"id": TEACHING_GROUPS["sv_4a"], "display_name": "Svenska 4A", "group_code": "SV4A",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"]]},
    {"id": TEACHING_GROUPS["sv_4b"], "display_name": "Svenska 4B", "group_code": "SV4B",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["sv_5ab"], "display_name": "Svenska 5", "group_code": "SV5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["sv_6ab"], "display_name": "Svenska 6", "group_code": "SV6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["sv_7a"], "display_name": "Svenska 7", "group_code": "SV7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["sv_gy1"], "display_name": "Svenska GY1", "group_code": "SVGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["sv_gy2"], "display_name": "Svenska GY2", "group_code": "SVGY2",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"]]},
    {"id": TEACHING_GROUPS["sv_gy3"], "display_name": "Svenska GY3", "group_code": "SVGY3",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # Math - Gimli teaches
    {"id": TEACHING_GROUPS["ma_4a"], "display_name": "Matematik 4A", "group_code": "MA4A",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"]]},
    {"id": TEACHING_GROUPS["ma_4b"], "display_name": "Matematik 4B", "group_code": "MA4B",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["ma_5ab"], "display_name": "Matematik 5", "group_code": "MA5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["ma_6ab"], "display_name": "Matematik 6", "group_code": "MA6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["ma_7a"], "display_name": "Matematik 7", "group_code": "MA7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["ma_gy1"], "display_name": "Matematik GY1", "group_code": "MAGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["ma_gy2"], "display_name": "Matematik GY2", "group_code": "MAGY2",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"]]},
    {"id": TEACHING_GROUPS["ma_gy3"], "display_name": "Matematik GY3", "group_code": "MAGY3",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # English - Éowyn teaches
    {"id": TEACHING_GROUPS["en_4a"], "display_name": "Engelska 4A", "group_code": "EN4A",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"]]},
    {"id": TEACHING_GROUPS["en_4b"], "display_name": "Engelska 4B", "group_code": "EN4B",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["en_5ab"], "display_name": "Engelska 5", "group_code": "EN5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["en_6ab"], "display_name": "Engelska 6", "group_code": "EN6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["en_7a"], "display_name": "Engelska 7", "group_code": "EN7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["en_gy1"], "display_name": "Engelska GY1", "group_code": "ENGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["en_gy2"], "display_name": "Engelska GY2", "group_code": "ENGY2",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"]]},
    {"id": TEACHING_GROUPS["en_gy3"], "display_name": "Engelska GY3", "group_code": "ENGY3",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # History - Celeborn teaches
    {"id": TEACHING_GROUPS["hi_5ab"], "display_name": "Historia 5", "group_code": "HI5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["hi_6ab"], "display_name": "Historia 6", "group_code": "HI6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["hi_7a"], "display_name": "Historia 7", "group_code": "HI7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["hi_gy1"], "display_name": "Historia GY1", "group_code": "HIGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["hi_gy2"], "display_name": "Historia GY2", "group_code": "HIGY2",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"]]},
    {"id": TEACHING_GROUPS["hi_gy3"], "display_name": "Historia GY3", "group_code": "HIGY3",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # Nature (NO) - Radagast/Círdan teach
    {"id": TEACHING_GROUPS["no_4ab"], "display_name": "NO 4", "group_code": "NO4",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"], GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["no_5ab"], "display_name": "NO 5", "group_code": "NO5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["no_6ab"], "display_name": "NO 6", "group_code": "NO6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["no_7a"], "display_name": "NO 7", "group_code": "NO7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["no_gy1"], "display_name": "Naturkunskap GY1", "group_code": "NKGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["no_gy2"], "display_name": "Naturkunskap GY2", "group_code": "NKGY2",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"]]},
    {"id": TEACHING_GROUPS["no_gy3"], "display_name": "Naturkunskap GY3", "group_code": "NKGY3",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # PE - Aragorn/Beorn teach
    {"id": TEACHING_GROUPS["id_4ab"], "display_name": "Idrott 4", "group_code": "ID4",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"], GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["id_5ab"], "display_name": "Idrott 5", "group_code": "ID5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["id_6ab"], "display_name": "Idrott 6", "group_code": "ID6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    {"id": TEACHING_GROUPS["id_7a"], "display_name": "Idrott 7", "group_code": "ID7",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["7a_erebor"]]},
    {"id": TEACHING_GROUPS["id_gy1"], "display_name": "Idrott GY1", "group_code": "IDGY1",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy1_fellowship"]]},
    {"id": TEACHING_GROUPS["id_gy23"], "display_name": "Idrott GY2-3", "group_code": "IDGY23",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_gymnasium"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["gy2_elven"], GROUPS["gy3_dunedain"], GROUPS["gy3_khazad"]]},
    # Art - Galadriel teaches
    {"id": TEACHING_GROUPS["bl_4ab"], "display_name": "Bild 4", "group_code": "BL4",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"], GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["bl_5ab"], "display_name": "Bild 5", "group_code": "BL5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["bl_6ab"], "display_name": "Bild 6", "group_code": "BL6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
    # Music - Glorfindel teaches
    {"id": TEACHING_GROUPS["mu_4ab"], "display_name": "Musik 4", "group_code": "MU4",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["4a_shire"], GROUPS["4b_buckland"]]},
    {"id": TEACHING_GROUPS["mu_5ab"], "display_name": "Musik 5", "group_code": "MU5",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["5a_gondor"], GROUPS["5b_rohan"]]},
    {"id": TEACHING_GROUPS["mu_6ab"], "display_name": "Musik 6", "group_code": "MU6",
     "group_type": "Undervisning", "organisation_id": ORGS["rivendell_grundskola"],
     "start_date": date(2024, 8, 15), "class_ids": [GROUPS["6a_rivendell"], GROUPS["6b_mirkwood"]]},
]

# Activities (lessons) - links teachers to teaching groups
ACTIVITIES_DATA = [
    # Swedish - Faramir
    {"id": ACTIVITIES["act_sv_4a"], "display_name": "Svenska 4A", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_4a"]]},
    {"id": ACTIVITIES["act_sv_4b"], "display_name": "Svenska 4B", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_4b"]]},
    {"id": ACTIVITIES["act_sv_5ab"], "display_name": "Svenska 5", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_5ab"]]},
    {"id": ACTIVITIES["act_sv_6ab"], "display_name": "Svenska 6", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_6ab"]]},
    {"id": ACTIVITIES["act_sv_7a"], "display_name": "Svenska 7", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_7a"]]},
    {"id": ACTIVITIES["act_sv_gy1"], "display_name": "Svenska GY1", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["faramir_staff"]], "group_ids": [TEACHING_GROUPS["sv_gy1"]]},
    {"id": ACTIVITIES["act_sv_gy2"], "display_name": "Svenska GY2", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["elrond"]], "group_ids": [TEACHING_GROUPS["sv_gy2"]]},
    {"id": ACTIVITIES["act_sv_gy3"], "display_name": "Svenska GY3", "subject_code": "SV",
     "subject_name": "Svenska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["elrond"]], "group_ids": [TEACHING_GROUPS["sv_gy3"]]},
    # Math - Gimli
    {"id": ACTIVITIES["act_ma_4a"], "display_name": "Matematik 4A", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_4a"]]},
    {"id": ACTIVITIES["act_ma_4b"], "display_name": "Matematik 4B", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_4b"]]},
    {"id": ACTIVITIES["act_ma_5ab"], "display_name": "Matematik 5", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_5ab"]]},
    {"id": ACTIVITIES["act_ma_6ab"], "display_name": "Matematik 6", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_6ab"]]},
    {"id": ACTIVITIES["act_ma_7a"], "display_name": "Matematik 7", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_7a"]]},
    {"id": ACTIVITIES["act_ma_gy1"], "display_name": "Matematik GY1", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["gimli"]], "group_ids": [TEACHING_GROUPS["ma_gy1"]]},
    {"id": ACTIVITIES["act_ma_gy2"], "display_name": "Matematik GY2", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["ma_gy2"]]},
    {"id": ACTIVITIES["act_ma_gy3"], "display_name": "Matematik GY3", "subject_code": "MA",
     "subject_name": "Matematik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["ma_gy3"]]},
    # English - Éowyn
    {"id": ACTIVITIES["act_en_4a"], "display_name": "Engelska 4A", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["eowyn_staff"]], "group_ids": [TEACHING_GROUPS["en_4a"]]},
    {"id": ACTIVITIES["act_en_4b"], "display_name": "Engelska 4B", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["eowyn_staff"]], "group_ids": [TEACHING_GROUPS["en_4b"]]},
    {"id": ACTIVITIES["act_en_5ab"], "display_name": "Engelska 5", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["eowyn_staff"]], "group_ids": [TEACHING_GROUPS["en_5ab"]]},
    {"id": ACTIVITIES["act_en_6ab"], "display_name": "Engelska 6", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["eowyn_staff"]], "group_ids": [TEACHING_GROUPS["en_6ab"]]},
    {"id": ACTIVITIES["act_en_7a"], "display_name": "Engelska 7", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["en_7a"]]},
    {"id": ACTIVITIES["act_en_gy1"], "display_name": "Engelska GY1", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["en_gy1"]]},
    {"id": ACTIVITIES["act_en_gy2"], "display_name": "Engelska GY2", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["en_gy2"]]},
    {"id": ACTIVITIES["act_en_gy3"], "display_name": "Engelska GY3", "subject_code": "EN",
     "subject_name": "Engelska", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["en_gy3"]]},
    # History - Celeborn
    {"id": ACTIVITIES["act_hi_5ab"], "display_name": "Historia 5", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_5ab"]]},
    {"id": ACTIVITIES["act_hi_6ab"], "display_name": "Historia 6", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_6ab"]]},
    {"id": ACTIVITIES["act_hi_7a"], "display_name": "Historia 7", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_7a"]]},
    {"id": ACTIVITIES["act_hi_gy1"], "display_name": "Historia GY1", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_gy1"]]},
    {"id": ACTIVITIES["act_hi_gy2"], "display_name": "Historia GY2", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_gy2"]]},
    {"id": ACTIVITIES["act_hi_gy3"], "display_name": "Historia GY3", "subject_code": "HI",
     "subject_name": "Historia", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["celeborn"]], "group_ids": [TEACHING_GROUPS["hi_gy3"]]},
    # Nature - Radagast & Círdan
    {"id": ACTIVITIES["act_no_4ab"], "display_name": "NO 4", "subject_code": "NO",
     "subject_name": "Naturorienterande ämnen", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["radagast"]], "group_ids": [TEACHING_GROUPS["no_4ab"]]},
    {"id": ACTIVITIES["act_no_5ab"], "display_name": "NO 5", "subject_code": "NO",
     "subject_name": "Naturorienterande ämnen", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["radagast"]], "group_ids": [TEACHING_GROUPS["no_5ab"]]},
    {"id": ACTIVITIES["act_no_6ab"], "display_name": "NO 6", "subject_code": "NO",
     "subject_name": "Naturorienterande ämnen", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["radagast"]], "group_ids": [TEACHING_GROUPS["no_6ab"]]},
    {"id": ACTIVITIES["act_no_7a"], "display_name": "NO 7", "subject_code": "NO",
     "subject_name": "Naturorienterande ämnen", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["no_7a"]]},
    {"id": ACTIVITIES["act_no_gy1"], "display_name": "Naturkunskap GY1", "subject_code": "NK",
     "subject_name": "Naturkunskap", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["no_gy1"]]},
    {"id": ACTIVITIES["act_no_gy2"], "display_name": "Naturkunskap GY2", "subject_code": "NK",
     "subject_name": "Naturkunskap", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["no_gy2"]]},
    {"id": ACTIVITIES["act_no_gy3"], "display_name": "Naturkunskap GY3", "subject_code": "NK",
     "subject_name": "Naturkunskap", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["cirdan"]], "group_ids": [TEACHING_GROUPS["no_gy3"]]},
    # PE - Aragorn & Beorn
    {"id": ACTIVITIES["act_id_4ab"], "display_name": "Idrott 4", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["aragorn"]], "group_ids": [TEACHING_GROUPS["id_4ab"]]},
    {"id": ACTIVITIES["act_id_5ab"], "display_name": "Idrott 5", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["aragorn"]], "group_ids": [TEACHING_GROUPS["id_5ab"]]},
    {"id": ACTIVITIES["act_id_6ab"], "display_name": "Idrott 6", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["beorn"]], "group_ids": [TEACHING_GROUPS["id_6ab"]]},
    {"id": ACTIVITIES["act_id_7a"], "display_name": "Idrott 7", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["beorn"]], "group_ids": [TEACHING_GROUPS["id_7a"]]},
    {"id": ACTIVITIES["act_id_gy1"], "display_name": "Idrott GY1", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["beorn"]], "group_ids": [TEACHING_GROUPS["id_gy1"]]},
    {"id": ACTIVITIES["act_id_gy23"], "display_name": "Idrott GY2-3", "subject_code": "IDH",
     "subject_name": "Idrott och hälsa", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_gymnasium"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["beorn"], PERSONS["aragorn"]], "group_ids": [TEACHING_GROUPS["id_gy23"]]},
    # Art - Galadriel
    {"id": ACTIVITIES["act_bl_4ab"], "display_name": "Bild 4", "subject_code": "BL",
     "subject_name": "Bild", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["galadriel"]], "group_ids": [TEACHING_GROUPS["bl_4ab"]]},
    {"id": ACTIVITIES["act_bl_5ab"], "display_name": "Bild 5", "subject_code": "BL",
     "subject_name": "Bild", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["galadriel"]], "group_ids": [TEACHING_GROUPS["bl_5ab"]]},
    {"id": ACTIVITIES["act_bl_6ab"], "display_name": "Bild 6", "subject_code": "BL",
     "subject_name": "Bild", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["galadriel"]], "group_ids": [TEACHING_GROUPS["bl_6ab"]]},
    # Music - Glorfindel
    {"id": ACTIVITIES["act_mu_4ab"], "display_name": "Musik 4", "subject_code": "MU",
     "subject_name": "Musik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["mu_4ab"]]},
    {"id": ACTIVITIES["act_mu_5ab"], "display_name": "Musik 5", "subject_code": "MU",
     "subject_name": "Musik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["mu_5ab"]]},
    {"id": ACTIVITIES["act_mu_6ab"], "display_name": "Musik 6", "subject_code": "MU",
     "subject_name": "Musik", "activity_type": "Undervisning",
     "organisation_id": ORGS["rivendell_grundskola"], "start_date": date(2024, 8, 15),
     "teacher_ids": [PERSONS["glorfindel"]], "group_ids": [TEACHING_GROUPS["mu_6ab"]]},
]
