#!/usr/bin/env python3
"""
CLI entry point for the anonymization pipeline.

Usage:
    python -m scripts.anonymize --dump path/to/dump.sql --seed 42
"""
import argparse
import sys
import os
import textwrap
from datetime import date

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.extract_from_dump import extract_tables
from scripts.schema_mapper import map_all


def write_anon_data(result: dict, output_path: str):
    """Write the anonymized data to a Python file matching lotr_data.py format."""
    lines = []
    lines.append('"""')
    lines.append("Anonymized production data for Demo SIS.")
    lines.append("Generated by scripts/anonymize.py — DO NOT EDIT MANUALLY.")
    lines.append("Contains zero real PII — safe to commit.")
    lines.append('"""')
    lines.append("from datetime import date")
    lines.append("")

    # ORGS
    lines.append("# Organisation UUIDs")
    lines.append("ORGS = {")
    for key, val in sorted(result["ORGS"].items()):
        lines.append(f'    "{key}": "{val}",')
    lines.append("}")
    lines.append("")

    # PERSONS
    lines.append("# Person UUIDs (staff, students, guardians)")
    lines.append("PERSONS = {")
    for key, val in sorted(result["PERSONS"].items()):
        lines.append(f'    "{key}": "{val}",')
    lines.append("}")
    lines.append("")

    # GROUPS
    lines.append("# Class group UUIDs")
    lines.append("GROUPS = {")
    for key, val in sorted(result["GROUPS"].items()):
        lines.append(f'    "{key}": "{val}",')
    lines.append("}")
    lines.append("")

    # TEACHING_GROUPS
    lines.append("# Teaching group UUIDs")
    lines.append("TEACHING_GROUPS = {")
    for key, val in sorted(result["TEACHING_GROUPS"].items()):
        lines.append(f'    "{key}": "{val}",')
    lines.append("}")
    lines.append("")

    # ACTIVITIES dict — generate from activities data
    lines.append("# Activity UUIDs")
    lines.append("ACTIVITIES = {")
    for i, act in enumerate(result["ACTIVITIES_DATA"]):
        key = f"act_{i}"
        lines.append(f'    "{key}": "{act["id"]}",')
    lines.append("}")
    lines.append("")

    # ORGANISATIONS
    lines.append("# Organisation hierarchy")
    lines.append("ORGANISATIONS = [")
    for org in result["ORGANISATIONS"]:
        lines.append("    {")
        for k, v in org.items():
            lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # STAFF
    lines.append(f"# Staff members ({len(result['STAFF'])})")
    lines.append("STAFF = [")
    for s in result["STAFF"]:
        lines.append("    {")
        for k, v in s.items():
            lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # STUDENTS
    lines.append(f"# Students ({len(result['STUDENTS'])})")
    lines.append("STUDENTS = [")
    for s in result["STUDENTS"]:
        lines.append("    {")
        for k, v in s.items():
            if k == "guardian_ids":
                id_strs = ", ".join(f'"{gid}"' for gid in v)
                lines.append(f'        "guardian_ids": [{id_strs}],')
            else:
                lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # GUARDIANS
    lines.append(f"# Guardians ({len(result['GUARDIANS'])})")
    lines.append("GUARDIANS = [")
    for g in result["GUARDIANS"]:
        lines.append("    {")
        for k, v in g.items():
            lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # GROUPS_DATA
    lines.append(f"# Class groups ({len(result['GROUPS_DATA'])})")
    lines.append("GROUPS_DATA = [")
    for g in result["GROUPS_DATA"]:
        lines.append("    {")
        for k, v in g.items():
            lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # TEACHING_GROUPS_DATA
    lines.append(f"# Teaching groups ({len(result['TEACHING_GROUPS_DATA'])})")
    lines.append("TEACHING_GROUPS_DATA = [")
    for g in result["TEACHING_GROUPS_DATA"]:
        lines.append("    {")
        for k, v in g.items():
            if k == "class_ids":
                id_strs = ", ".join(f'"{cid}"' for cid in v)
                lines.append(f'        "class_ids": [{id_strs}],')
            else:
                lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    # ACTIVITIES_DATA
    lines.append(f"# Activities ({len(result['ACTIVITIES_DATA'])})")
    lines.append("ACTIVITIES_DATA = [")
    for act in result["ACTIVITIES_DATA"]:
        lines.append("    {")
        for k, v in act.items():
            if k in ("teacher_ids", "group_ids"):
                id_strs = ", ".join(f'"{tid}"' for tid in v)
                lines.append(f'        "{k}": [{id_strs}],')
            else:
                lines.append(f"        {_format_kv(k, v, result)},")
        lines.append("    },")
    lines.append("]")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")


def _format_kv(key: str, value, result: dict) -> str:
    """Format a key-value pair for Python source output."""
    if value is None:
        return f'"{key}": None'
    elif isinstance(value, bool):
        return f'"{key}": {value}'
    elif isinstance(value, int):
        return f'"{key}": {value}'
    elif isinstance(value, date):
        return f'"{key}": date({value.year}, {value.month}, {value.day})'
    elif isinstance(value, list):
        items = ", ".join(f'"{v}"' for v in value)
        return f'"{key}": [{items}]'
    else:
        # Escape quotes in string values
        escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
        return f'"{key}": "{escaped}"'


def main():
    parser = argparse.ArgumentParser(
        description="Anonymize a skolSköld production database dump"
    )
    parser.add_argument(
        "--dump", required=True,
        help="Path to the pg_dump SQL file"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for deterministic anonymization (default: 42)"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output file path (default: app/seed/anon_data.py)"
    )

    args = parser.parse_args()

    if not os.path.exists(args.dump):
        print(f"Error: dump file not found: {args.dump}")
        sys.exit(1)

    output_path = args.output or os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "app", "seed", "anon_data.py"
    )

    print(f"Parsing dump: {args.dump}")
    data = extract_tables(args.dump)

    print("Table counts:")
    for table, rows in sorted(data.items()):
        print(f"  {table}: {len(rows)} rows")

    print(f"\nAnonymizing with seed={args.seed}...")
    result = map_all(data, seed=args.seed)

    print(f"\nMapped entities:")
    print(f"  Organisations: {len(result['ORGANISATIONS'])}")
    print(f"  Staff: {len(result['STAFF'])}")
    print(f"  Students: {len(result['STUDENTS'])}")
    print(f"  Guardians: {len(result['GUARDIANS'])}")
    print(f"  Class groups: {len(result['GROUPS_DATA'])}")
    print(f"  Teaching groups: {len(result['TEACHING_GROUPS_DATA'])}")
    print(f"  Activities: {len(result['ACTIVITIES_DATA'])}")

    print(f"\nWriting output to: {output_path}")
    write_anon_data(result, output_path)
    print("Done!")


if __name__ == "__main__":
    main()
