"""
Swedish name pools for anonymization.
Sourced from SCB (Statistiska centralbyrån) public top-names data.
"""

MALE_FIRST_NAMES = [
    "Erik", "Lars", "Karl", "Anders", "Johan", "Per", "Nils", "Lennart",
    "Mikael", "Olof", "Jan", "Axel", "Gunnar", "Sven", "Fredrik", "Hans",
    "Peter", "Thomas", "Daniel", "Magnus", "Henrik", "Björn", "Bo", "Ulf",
    "Bengt", "Åke", "Leif", "Göran", "Mats", "Martin", "Stefan", "Rolf",
    "Ingemar", "Christer", "Gustav", "Arne", "Kent", "Roger", "Jonas",
    "Christian", "Patrik", "David", "Oskar", "Jakob", "Mattias", "Rickard",
    "Marcus", "Emil", "Viktor", "Sebastian", "Filip", "Anton", "Simon",
    "Alexander", "William", "Lucas", "Hugo", "Elias", "Oliver", "Noah",
    "Liam", "Adam", "Isak", "Leo", "Theo", "Albin", "Alfred", "Arvid",
    "Edvin", "Melvin", "Ludvig", "Viggo", "Ebbe", "Valter", "Sixten",
    "Ivar", "Folke", "Torbjörn", "Staffan", "Stig", "Tore", "Ragnar",
    "Bertil", "Harald", "Ingvar", "Olov", "Sten", "Claes", "Håkan",
    "Kjell", "Tommy", "Rune", "Alf", "Roland", "Torsten", "Kurt",
    "Allan", "Conny", "Bernt", "Jörgen", "Kenneth", "Linus", "Tobias",
    "Jonathan", "Pontus", "Robert", "Joakim", "Andreas", "Carl", "Niklas",
    "Josef", "Max", "Gabriel", "Samuel", "Benjamin", "Hampus", "Rasmus",
    "Kevin", "Dennis", "Robin", "Tim", "Kim", "Felix", "Jesper",
    "Christoffer", "John", "Joel", "Victor", "Lukas", "Noel", "Elliot",
    "Vincent", "Dante", "Wilmer", "Malte", "Casper", "Charlie", "Loke",
    "Otis", "Milo", "Otto", "Sigge", "Frank", "Ture", "Algot",
    "Harry", "Vilgot", "Love", "Måns", "Ted", "Olle", "Knut",
    "Tage", "Holger", "Helmer", "Gunne", "Egon", "Bror", "Birger",
    "Evert", "Hilding", "Fridolf", "Gottfrid", "Hjalmar", "Eskil",
    "Torkel", "Vidar", "Tryggve", "Stellan", "Petter", "Ville",
    "Ruben", "Aron", "Melker", "Svante", "Lage", "Yngve", "Gillis",
    "Morgan", "Nikita", "Alex", "Sam", "Maximilian", "Theodor",
    "Henning", "Tomas", "Ola", "Hans-Erik", "Lars-Erik", "Karl-Erik",
    "Anders", "Jan-Erik", "Per-Olof", "Sven-Erik", "Nils-Erik",
    "Sture", "Göte", "Örjan", "Vilhelm", "Georg", "Erland", "Alvar",
    "Bruno", "Sixten", "Eskil", "Torbjörn", "Gerhard", "Rudolf",
]

FEMALE_FIRST_NAMES = [
    "Maria", "Anna", "Margareta", "Elisabeth", "Eva", "Kristina",
    "Birgitta", "Karin", "Elisabet", "Marie", "Ingrid", "Christina",
    "Linnéa", "Sofia", "Kerstin", "Marianne", "Lena", "Helena",
    "Sara", "Emma", "Johanna", "Inga", "Elin", "Katarina", "Annika",
    "Susanne", "Cecilia", "Monica", "Ulla", "Barbro", "Gunilla",
    "Anita", "Astrid", "Britt", "Maj", "Berit", "Inga-Lill", "Gun",
    "Siv", "Yvonne", "Solveig", "Ann", "Carina", "Camilla", "Malin",
    "Jenny", "Linda", "Frida", "Hanna", "Amanda", "Emilia", "Julia",
    "Ida", "Matilda", "Wilma", "Klara", "Maja", "Alice", "Ella",
    "Ebba", "Saga", "Agnes", "Freja", "Stella", "Olivia", "Vera",
    "Alma", "Astrid", "Elsa", "Nora", "Felicia", "Lovisa", "Alva",
    "Lilly", "Signe", "Tyra", "Tuva", "Tilda", "Ines", "Iris",
    "Hilma", "Stina", "Edith", "Molly", "Märta", "Hedvig", "Greta",
    "Ingeborg", "Dagny", "Eleonora", "Birgit", "Ragnhild", "Sigrid",
    "Gunborg", "Britt-Marie", "Ann-Marie", "Maud", "Gurli", "Gertrud",
    "Margit", "Gerd", "Irene", "Rut", "Viola", "Dagmar", "Doris",
    "Elna", "Svea", "Adina", "Agda", "Alva", "Vendela", "Filippa",
    "Elvira", "Lova", "Selma", "Thea", "Juni", "Ellen", "Minna",
    "Ronja", "Leah", "Nellie", "Ellie", "Livia", "Isabelle", "Moa",
    "Nova", "Penny", "Lykke", "Alba", "Siri", "Vilda", "Luna",
    "Melissa", "Jasmine", "Sandra", "Jessica", "Victoria", "Therese",
    "Louise", "Rebecca", "Caroline", "Charlotte", "Petra", "Diana",
    "Alexandra", "Veronica", "Ulrika", "Åsa", "Helen", "Ingela",
    "Agneta", "Märit", "Bodil", "Rigmor", "Maj-Britt", "Ann-Christin",
    "Gun-Britt", "Inga-Britt", "Margaretha", "Gudrun", "Eivor",
    "Gullan", "Hjördis", "Hildur", "Ottilia", "Dagmar", "Britta",
    "Torborg", "Alfhild", "Gunhild", "Helga", "Ragnhild", "Solbritt",
    "Tora", "Aina", "Daga", "Elisif", "Liv", "Mie", "Nathalie",
    "Nadja", "Sanna", "Tove", "Ylva", "Lovisa", "Cornelia", "Daniela",
    "Emelie", "Josefin", "Kajsa", "Lina", "Mikaela", "Nina", "Paulina",
]

LAST_NAMES = [
    "Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson",
    "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson",
    "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson",
    "Jönsson", "Lindberg", "Jakobsson", "Magnusson", "Olofsson",
    "Lindström", "Lindqvist", "Lindgren", "Axelsson", "Berg",
    "Bergström", "Lundberg", "Lundgren", "Lundqvist", "Mattsson",
    "Berglund", "Fredriksson", "Sandberg", "Henriksson", "Forsberg",
    "Sjöberg", "Wallin", "Engström", "Eklund", "Danielsson",
    "Lundin", "Håkansson", "Björk", "Bergman", "Gunnarsson",
    "Holm", "Wikström", "Samuelsson", "Fransson", "Isaksson",
    "Bergqvist", "Nyström", "Holmberg", "Arvidsson", "Löfgren",
    "Söderberg", "Nyberg", "Blomqvist", "Claesson", "Mårtensson",
    "Nordström", "Lundström", "Eliasson", "Pålsson", "Viklund",
    "Björklund", "Berggren", "Sandström", "Lund", "Nordin",
    "Ström", "Åberg", "Hermansson", "Ekström", "Holmgren",
    "Hedlund", "Sundberg", "Dahlberg", "Falk", "Hellström",
    "Sjögren", "Abrahamsson", "Martinsson", "Öberg", "Andreasson",
    "Strömberg", "Månsson", "Hansen", "Åkesson", "Dahl",
    "Lindblom", "Norberg", "Sundström", "Ståhl", "Ahlström",
    "Boman", "Bäckström", "Edlund", "Elofsson", "Engberg",
    "Granberg", "Granlund", "Hedström", "Hellberg", "Holmqvist",
    "Höglund", "Ivarsson", "Jonasson", "Lind", "Lindahl",
    "Lindblad", "Moberg", "Nordberg", "Nordlund", "Nyman",
    "Nygren", "Ohlsson", "Palm", "Petersson", "Ringström",
    "Rosén", "Rubensson", "Segerlund", "Sjöblom", "Solberg",
    "Sundqvist", "Thorén", "Wahlström", "Wennerström", "Westberg",
    "Widén", "Zetterlund", "Ahlgren", "Almqvist", "Backlund",
    "Berntsson", "Björnsson", "Bäckman", "Carlsson", "Dahlgren",
    "Edström", "Ekberg", "Elfström", "Engdahl", "Eriksen",
    "Fagerström", "Göransson", "Hagberg", "Hallberg", "Hedberg",
    "Holmström", "Hägglund", "Häggström", "Klasson", "Lidström",
    "Liljeberg", "Malmberg", "Malmqvist", "Nilsen", "Norén",
    "Olausson", "Ottosson", "Paulsson", "Ramström", "Rydberg",
    "Rönnqvist", "Sellström", "Sjöström", "Skoglund", "Stenberg",
    "Stenmark", "Sundelin", "Svärd", "Söderström", "Vesterlund",
    "Vikström", "Westerberg", "Öhman", "Östlund", "Ågren",
    "Blom", "Borg", "Ekman", "Hallgren", "Hedman",
    "Holmén", "Hultgren", "Hultqvist", "Hult", "Isacsson",
    "Johannesson", "Kjellberg", "Kraft", "Landström", "Levin",
    "Ljung", "Malmström", "Melin", "Modin", "Molin",
    "Nilstam", "Nordqvist", "Norrman", "Ohlson", "Oskarsson",
    "Palmqvist", "Rehn", "Roos", "Sahlin", "Severin",
    "Skarsgård", "Skog", "Stenström", "Storm", "Sund",
    "Tegnér", "Vikman", "Wahl", "Welin", "Åström",
]

STREET_NAMES = [
    "Storgatan", "Kungsgatan", "Drottninggatan", "Vasagatan", "Sveavägen",
    "Birger Jarlsgatan", "Götgatan", "Hornsgatan", "Ringvägen", "Odengatan",
    "Karlavägen", "Valhallavägen", "Fleminggatan", "Sankt Eriksgatan",
    "Norrtullsgatan", "Dalagatan", "Surbrunnsgatan", "Tegnérgatan",
    "Hantverkargatan", "Kungsholmsgatan", "Scheelegatan", "Pontonjärgatan",
    "Alströmergatan", "Fridhemsplan", "Bergsgatan", "Pipersgatan",
    "Polhemsgatan", "Rålambsvägen", "Lindhagensgatan", "Stadshagen",
    "Roslagsgatan", "Luntmakargatan", "Döbelnsgatan", "Torsgatan",
    "Norrlandsgatan", "Regeringsgatan", "Malmskillnadsgatan", "Klarabergsgatan",
    "Hamngatan", "Biblioteksgatan", "Sturegatan", "Narvavägen",
    "Banérgatan", "Grevgatan", "Artillerigatan", "Kommendörsgatan",
    "Skeppargatan", "Östermalmsgatan", "Brahegatan", "Engelbrektsgatan",
]

POSTAL_CODE_CITY = [
    ("111 22", "Stockholm"), ("111 34", "Stockholm"), ("112 46", "Stockholm"),
    ("113 57", "Stockholm"), ("114 28", "Stockholm"), ("115 21", "Stockholm"),
    ("116 43", "Stockholm"), ("117 33", "Stockholm"), ("118 26", "Stockholm"),
    ("120 44", "Stockholm"), ("126 30", "Hägersten"), ("127 35", "Skärholmen"),
    ("131 45", "Nacka"), ("141 46", "Huddinge"), ("151 72", "Södertälje"),
    ("162 67", "Vällingby"), ("167 51", "Bromma"), ("171 64", "Solna"),
    ("172 68", "Sundbyberg"), ("181 47", "Lidingö"),
]
